services:
  mkdocs-material:
    image: ${DOCKER_IMAGE_LATEST}
    container_name: mkdocs-${USER}
    volumes:
      - ${PWD}:/docs
    networks:
      - mkdocs-material-net
    ports:
      - ${PORT}:8000
    restart: always

networks:
  mkdocs-material-net:
